---
title: "test ccnv"
output: html_document
date: "2024-05-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read data and check data}
#for Mac
target_files <- read.csv("/Volumes/PhD/Ependymoma/Ependymoma_methylation_mainCohort/sample_info_02_08_2022_850_Mac.csv", header=TRUE, sep=";")

#
g_files <- paste0(target_files$Basename, "_Grn.idat")
r_files <- paste0(target_files$Basename,"_Red.idat" )

# test if every file is an idat file
test_grn <- sapply(g_files, readChar, nchars = 4)
test_red <- sapply(r_files, readChar, nchars = 4)

#This will give out file names if they are not IDAT and character 0 if all files are IDAT
test_grn[test_grn != "IDAT"]
test_red[test_red != "IDAT"]

#remove duplicates
while (anyDuplicated(target_files$Basename) != "0") {
  target_files <- target_files[-anyDuplicated(target_files$Basename),]
}

PFB2_5 <- target_files[which(target_files$Classifier_new_version_condensed == "EPN_PFB_1_to_5"),]
PFB2_5 <- PFB2_5[-which(PFB2_5$Classifier_new_version == "EPN_PFB_1"),]

cumul.CNV(PFB2_5, segmentationMode = "multi")

pfb <- cumul.CNV(PFB2_5, segmentationMode = "multi", out = "data")
#details <- read.csv("/Volumes/PhD/Ependymoma/Ependymoma_methylation_mainCohort/detail_conumee.csv")
#detail_regions <- details$name

```

```{r testing mouse}
#for Mac
target_files <- read.csv("/Volumes/PhD/Maus_idats_Melanie/IDH_H3WT_hGFAP_cre_P53_Lin28A_Primarytumor/MausIdats1.csv", header=TRUE, sep=";")

#
g_files <- paste0(target_files$Basename, "_Grn.idat")
r_files <- paste0(target_files$Basename,"_Red.idat" )

# test if every file is an idat file
test_grn <- sapply(g_files, readChar, nchars = 4)
test_red <- sapply(r_files, readChar, nchars = 4)

#This will give out file names if they are not IDAT and character 0 if all files are IDAT
test_grn[test_grn != "IDAT"]
test_red[test_red != "IDAT"]

#remove duplicates
while (anyDuplicated(target_files$Basename) != "0") {
  target_files <- target_files[-anyDuplicated(target_files$Basename),]
  
}

controlfiles <- read.csv("/Volumes/PhD/Maus_idats_Melanie/IDH_H3WT_hGFAP_cre_P53_Primarytumor/MausIdats2.csv", header = TRUE, sep = ";")

g_files <- paste0(controlfiles$Basename, "_Grn.idat")
r_files <- paste0(controlfiles$Basename,"_Red.idat" )

# test if every file is an idat file
test_grn <- sapply(g_files, readChar, nchars = 4)
test_red <- sapply(r_files, readChar, nchars = 4)

#This will give out file names if they are not IDAT and character 0 if all files are IDAT
test_grn[test_grn != "IDAT"]
test_red[test_red != "IDAT"]

#remove duplicates
while (anyDuplicated(controlfiles$Basename) != "0") {
  controlfiles <- controlfiles[-anyDuplicated(controlfiles$Basename),]
  
}
cumul.CNV(target_files, controls = controlfiles)

cumul.CNV(PFB2_5, segmentationMode = "multi")

```

